-- Baseline schema for orderdb.
CREATE TABLE orders (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT         NOT NULL,
    quantity    INTEGER        NOT NULL,
    total_price NUMERIC(19, 2) NOT NULL,
    status      VARCHAR(32)    NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
