CREATE TABLE order_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES orders (id),
    line_number    INTEGER NOT NULL,
    product_id     BIGINT NOT NULL,
    reservation_id UUID NOT NULL,
    product_name   VARCHAR(255) NOT NULL,
    unit_price     NUMERIC(19, 2) NOT NULL,
    quantity       INTEGER NOT NULL,
    CONSTRAINT uq_order_items_line UNIQUE (order_id, line_number),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0)
);

INSERT INTO order_items (order_id, line_number, product_id, reservation_id,
                         product_name, unit_price, quantity)
SELECT id, 0, product_id, reservation_id, 'legacy', total_price / quantity, quantity
FROM orders
WHERE product_id IS NOT NULL AND reservation_id IS NOT NULL;
