CREATE TABLE order_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES orders (id),
    sequence        INTEGER NOT NULL,
    from_status     VARCHAR(32),
    to_status       VARCHAR(32) NOT NULL,
    transitioned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_order_status_history_sequence UNIQUE (order_id, sequence)
);

INSERT INTO order_status_history (order_id, sequence, from_status, to_status, transitioned_at)
SELECT id, 0, NULL, status, created_at
FROM orders;
