-- Baseline schema for orderdb. Replaces `ddl-auto: update`, which changed the
-- schema silently, had no version and no way back.
--
-- Written in portable SQL so the same file runs on H2 (dev/test) and Postgres
-- (docker compose). That is deliberate: a migration only exercised by
-- `docker compose up` is a migration nobody tests.
--
-- Table is "orders", not "order" — ORDER is a reserved word in SQL.
CREATE TABLE orders (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT         NOT NULL,
    quantity    INTEGER        NOT NULL,
    total_price NUMERIC(19, 2) NOT NULL,
    status      VARCHAR(32)    NOT NULL,
    -- Instant maps to TIMESTAMP WITH TIME ZONE in Hibernate 6, not a naive timestamp.
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
