-- Baseline schema for productdb. Replaces `ddl-auto: update`, which changed the
-- schema silently, had no version and no way back.
--
-- Written in portable SQL so the same file runs on H2 (dev/test) and Postgres
-- (docker compose). That is deliberate: a migration only exercised by
-- `docker compose up` is a migration nobody tests.
--
-- GENERATED BY DEFAULT AS IDENTITY is the ANSI form of BIGSERIAL. Postgres 10+
-- and H2 both accept it, and it matches GenerationType.IDENTITY.
CREATE TABLE product (
    id      BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)   NOT NULL,
    price   NUMERIC(19, 2) NOT NULL,
    stock   INTEGER        NOT NULL,
    -- NOT NULL is safe: Hibernate writes @Version = 0 on the INSERT itself.
    version BIGINT         NOT NULL
);
