-- Stock stops being a counter and becomes a projection of an append-only ledger.
--
-- product.stock stays: it is the fast read, and it is what SELECT ... FOR UPDATE
-- locks. What changes is that it is no longer the source of truth. Every future
-- balance must satisfy:
--
--     SUM(stock_movement.quantity) == product.stock
--
-- Quantity is signed rather than absolute-plus-a-direction-flag, so the balance is a
-- plain SUM and there is no second column that can contradict the first.
CREATE TABLE stock_movement (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT      NOT NULL REFERENCES product (id),
    quantity    INTEGER     NOT NULL,
    type        VARCHAR(16) NOT NULL,
    -- Only ADJUSTMENT carries one; the other types explain themselves.
    reason_code VARCHAR(16),
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- The enum names are enforced by the database, not only by @Enumerated(STRING).
    -- Hibernate's `validate` compares tables, columns and base types — never CHECK
    -- constraints — so a bad value written by anything other than this application
    -- would otherwise land silently and poison the balance.
    CONSTRAINT ck_stock_movement_type
        CHECK (type IN ('RECEIPT', 'ISSUE', 'RELEASE', 'ADJUSTMENT')),
    CONSTRAINT ck_stock_movement_reason
        CHECK (reason_code IS NULL OR reason_code IN ('CYCLE_COUNT', 'DAMAGE', 'CORRECTION')),
    -- A zero-quantity line is not an event; it is noise that survives forever.
    CONSTRAINT ck_stock_movement_nonzero CHECK (quantity <> 0)
);

-- Every read of the ledger is "all lines for this product, in order".
CREATE INDEX idx_stock_movement_product ON stock_movement (product_id, occurred_at);

-- Backfill: rows created under V1 have stock but no movements, so the invariant above
-- would be false for them from the very first check. Treat their current balance as an
-- opening receipt. Doing this in the migration rather than in application code is the
-- point — the invariant holds for every row in the table, not only for rows written by
-- the new code path.
INSERT INTO stock_movement (product_id, quantity, type, occurred_at)
SELECT id, stock, 'RECEIPT', CURRENT_TIMESTAMP
FROM product
WHERE stock > 0;
