-- Baseline schema for productdb.
CREATE TABLE product (
    id      BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)   NOT NULL,
    price   NUMERIC(19, 2) NOT NULL,
    stock   INTEGER        NOT NULL,
    version BIGINT         NOT NULL
);
