-- Stock is projected from an append-only ledger.
CREATE TABLE stock_movement (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT      NOT NULL REFERENCES product (id),
    quantity    INTEGER     NOT NULL,
    type        VARCHAR(16) NOT NULL,
    reason_code VARCHAR(16),
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_stock_movement_type
        CHECK (type IN ('RECEIPT', 'ISSUE', 'RELEASE', 'ADJUSTMENT')),
    CONSTRAINT ck_stock_movement_reason
        CHECK (reason_code IS NULL OR reason_code IN ('CYCLE_COUNT', 'DAMAGE', 'CORRECTION')),
    CONSTRAINT ck_stock_movement_nonzero CHECK (quantity <> 0)
);

CREATE INDEX idx_stock_movement_product ON stock_movement (product_id, occurred_at);

INSERT INTO stock_movement (product_id, quantity, type, occurred_at)
SELECT id, stock, 'RECEIPT', CURRENT_TIMESTAMP
FROM product
WHERE stock > 0;
